レビューを参考にしたスクリプト修正
tricore-as14/TricoreTeamProject pull request #13
Opened 2023-10-31 07:48 UTC by tricore-as14

レビューで指摘していただいた箇所のスクリプトを修正いたしました。
・ScriptフォルダにStageSelectフォルダとTitleフォルダを作成し、各スクリプトをフォルダ分けした
・タイトルシーン、ステージ選択シーンからのシーン遷移をライブラリを使用したものに変更
・ゲームシーンが格納されているファイルを参照し、ゲームシーンの個数分、ボタンのプレハブを生成
・Actionを使用し、押されたボタンのインデックスを取得し、保存する関数を、ボタンが押された時に呼び出すようにした
・データを保存するファイルのパスを指定する部分に、文字列補間を使用
・Instantiateを使用したコンポーネント取得

2023-10-31 09:18 UTC, tricore-as03 requested changes

2023-10-31 09:18 UTC, tricore-as03 commented on Assets/MyGameAssets/Script/SelectStage/StageSelectUIManager.cs
> +            int sceneAIndex = SceneUtility.GetBuildIndexByScenePath($"Assets/MyGameAssets/GameScene/Stage_{i}.unity");
[MUST]
`Stage_{i}`でシーン名を作ってますが「StageSelectButton 」クラスでも`$"Stage_{stageNumber}`でシーン名を作ってるので共通化してほしいです。

2023-10-31 09:18 UTC, tricore-as03 commented on Assets/MyGameAssets/Script/Title/ButtonSceneChanger.cs
> +public class ButtonSceneChanger : MonoBehaviour
[MUST]
クラスコメントは書いてください。

2023-10-31 09:18 UTC, tricore-as03 commented on Assets/MyGameAssets/Script/SelectStage/StageSelectUIManager.cs
> +                buttonEvent.OnPressButtonEvent += SavePressButtonIndex;
[MUST]
+=で登録したイベントは、終了時に-=で解除してください。
登録されっぱなしになり、メモリリークを起こす恐れがあります。

2023-11-01 03:23 UTC, tricore-as03 requested changes

2023-11-01 03:23 UTC, tricore-as03 commented on Assets/MyGameAssets/Script/SelectStage/StageSelectButton.cs
> +    [SerializeField] SceneChanger sceneChanger;     // ライブラリのシーン切り替えスクリプト
[Q]
修正方針で一点気になったので質問です。
SceneChangerのSceneName（string）でシーンを設定する形に変更してますが、StageManagerクラスではenumのChoiceStageでシーンを設定する形になっていて、stringとenumで設定方法が混在してしまってます。
これらは後の対応で統一される認識で合ってますか？

2023-11-01 03:52 UTC, tricore-as14 commented on Assets/MyGameAssets/Script/SelectStage/StageSelectButton.cs
> +    [SerializeField] SceneChanger sceneChanger;     // ライブラリのシーン切り替えスクリプト
はい、シーン遷移部分の実装については話し合う予定でした。
後ほど話し合おうと思います。

2023-11-01 03:59 UTC, tricore-as14 commented on Assets/MyGameAssets/Script/StageSelectUIManager.cs
> +        while (true)
SceneManager.sceneCountInBuildSettings の値を使用したfor文での処理に変更いたしました。

2023-11-01 04:00 UTC, tricore-as14 commented on Assets/MyGameAssets/Script/SelectStage/StageSelectUIManager.cs
> +            int sceneAIndex = SceneUtility.GetBuildIndexByScenePath($"Assets/MyGameAssets/GameScene/Stage_{i}.unity");
Stage_{stageNumber} のほうに統一いたしました。

2023-11-01 04:00 UTC, tricore-as14 commented on Assets/MyGameAssets/Script/Title/ButtonSceneChanger.cs
> +public class ButtonSceneChanger : MonoBehaviour
クラスコメントを記述いたしました。

2023-11-01 04:02 UTC, tricore-as14 commented on Assets/MyGameAssets/Script/SelectStage/StageSelectUIManager.cs
> +                buttonEvent.OnPressButtonEvent += SavePressButtonIndex;
OnDestroy が呼ばれた際にイベントを削除するように実装いたしました。

2023-11-01 04:16 UTC, tricore-as03 commented on Assets/MyGameAssets/Script/SelectStage/StageSelectUIManager.cs
> +            int sceneAIndex = SceneUtility.GetBuildIndexByScenePath($"Assets/MyGameAssets/GameScene/Stage_{i}.unity");
説明が足りていなかったようで申し訳ないです。
記述の「統一」ではなく、処理の「共通化」を行ってほしいです。
現状、双方で「Stage_」と文字列を直打ちしてステージ名を作っているので、シーンの番号を渡したらシーン名を返してくれるような関数を作り処理の共通化を行ってほしいです。
意図としては、現状だと仮にシーン名が変更になった場合に、２か所の文字列を修正する必要があり、修正漏れ等のミスに繋がる恐れがあるためです。

2023-11-01 07:11 UTC, tricore-as14 commented on Assets/MyGameAssets/Script/SelectStage/StageSelectUIManager.cs
> +            int sceneAIndex = SceneUtility.GetBuildIndexByScenePath($"Assets/MyGameAssets/GameScene/Stage_{i}.unity");
OtherFunction クラスを作成し、その中にシーン名を作る関数を実装し、
関数を利用した処理の共通化を行いました。

2023-11-01 07:29 UTC, tricore-as03 requested changes

2023-11-01 07:29 UTC, tricore-as03 commented on Assets/MyGameAssets/Script/OtherFunction.cs
> +public class OtherFunction : MonoBehaviour
[MUST]
ステージの汎用機能をまとめたクラスなので「StageUtility」で良いと思います。
OtherFunctionだと、どんな機能がまとめられているのか分からないです。

2023-11-01 07:29 UTC, tricore-as03 commented on Assets/MyGameAssets/Script/OtherFunction.cs
> +public class OtherFunction : MonoBehaviour
[MUST]
MonoBehaviorを継承する必要はないと思います。
また、汎用的に使用する関数なのでstatic関数にしてどこからでも呼べる形にしてしまって問題ないと思います。

2023-11-01 07:29 UTC, tricore-as03 commented on Assets/MyGameAssets/Script/SelectStage/StageSelectButton.cs
> +    OtherFunction otherFunction = new OtherFunction();  // 汎用的な関数をまとめたクラス
[MUST]
static関数にしてしまえば、newでインスタンスを生成する必要はなくなると思います。

2023-11-01 07:29 UTC, tricore-as03 commented on Assets/MyGameAssets/Script/SelectStage/StageSelectUIManager.cs
> +    OtherFunction otherFunction = new OtherFunction();  // 汎用的な関数をまとめたクラス
[MUST]
こちらも同様に不要になると思います。

2023-11-01 07:44 UTC, tricore-as14 commented on Assets/MyGameAssets/Script/OtherFunction.cs
> +public class OtherFunction : MonoBehaviour
クラス名を「StageUtility」に修正いたしました。

2023-11-01 07:45 UTC, tricore-as14 commented on Assets/MyGameAssets/Script/OtherFunction.cs
> +public class OtherFunction : MonoBehaviour
MonoBehaviorの継承を削除し、
関数をstatic関数に修正いたしました。

2023-11-01 07:45 UTC, tricore-as14 commented on Assets/MyGameAssets/Script/SelectStage/StageSelectButton.cs
> +    OtherFunction otherFunction = new OtherFunction();  // 汎用的な関数をまとめたクラス
該当部分を削除し、修正いたしました。

2023-11-01 07:45 UTC, tricore-as14 commented on Assets/MyGameAssets/Script/SelectStage/StageSelectUIManager.cs
> +    OtherFunction otherFunction = new OtherFunction();  // 汎用的な関数をまとめたクラス
該当部分を削除し、修正いたしました。

2023-11-01 07:50 UTC, tricore-as03 approved these changes
LGTM

2023-11-01 07:55 UTC, merged