ゲームシーンのUIの追加とスクリプトを各UI個別での処理へ変更
tricore-as14/TricoreTeamProject pull request #14
Opened 2023-10-31 08:10 UTC by tricore-as13

・フォントの追加と変更
・画像の追加
・ゲームオーバー時のフォント追加とコントローラースクリプト追加
・カウントダウン中の画像追加のコントローラースクリプトの追加
・UIコントローラーを具材の残り個数を表示するUiコントローラー、ボタンUIコントローラー、カウントダウンUIコントローラーに分割

2023-10-31 08:49 UTC, tricore-as03 requested changes

2023-10-31 08:49 UTC, tricore-as03 commented on Assets/MyGameAssets/Script/Stage/CountDownUIController.cs
> +    readonly float initialFillAmount = 1.0f;
[MUST]
定数はアッパーキャメルケースです。

2023-10-31 08:49 UTC, tricore-as03 commented on Assets/MyGameAssets/Script/Stage/CountDownUIController.cs
> +
[MUST]
一行隙間が空いてます。

2023-10-31 08:49 UTC, tricore-as03 commented on Assets/MyGameAssets/Script/Stage/ButtonUIController.cs
> +﻿using UnityEngine;
[MUST]
「ButtonUIController」
「IngredientsCounterUIController」
「GameOverTextController 」
これらのＵＩクラスですが、MonoBehaviorのクラスにしては処理が単純すぎるので、ステージ全体のＵＩを管理するようなクラス（例：StageUI）を作り、それにまとめてしまったほうが良いかと。
「CountDownUIController」については、StageUIにSerializeFieldで持たせて、「StageManager」→「StageUI」→「CountDownUIController」経由で処理を呼び出すような形にするのが良いかと思います。

2023-10-31 08:49 UTC, tricore-as03 commented on Assets/MyGameAssets/Script/Stage/CountDownUIController.cs
> +        time = 0; // 時間初期化
[MUST]
この辺りの処理がコピペなので関数化できないでしょうか？
IEnumerator型の関数（例：Countdown）を別で作り、yield return Countdownと書くことで、コルーチンの中で別のコルーチンの処理を待つことができます。
https://alpacatech.hateblo.jp/entry/2018/04/05/183207

2023-11-01 02:47 UTC, tricore-as13 commented on Assets/MyGameAssets/Script/Stage/CountDownUIController.cs
> +    readonly float initialFillAmount = 1.0f;
修正いたしました。

2023-11-01 02:47 UTC, tricore-as13 commented on Assets/MyGameAssets/Script/Stage/CountDownUIController.cs
> +
修正いたしました。

2023-11-01 02:51 UTC, tricore-as13 commented on Assets/MyGameAssets/Script/Stage/ButtonUIController.cs
> +﻿using UnityEngine;
StageUIManagerがUI全体を保持しCountDownUIControllerは例外処理として独立存在としStageUIManagerのみが情報を保持してる状態にしStageManagerからStageUIManager経由での呼び出し処理に変更しました。

2023-11-01 02:51 UTC, tricore-as13 commented on Assets/MyGameAssets/Script/Stage/CountDownUIController.cs
> +        time = 0; // 時間初期化
関数化して修正いたしました。

2023-11-01 03:21 UTC, tricore-as03 approved these changes
LGTM

2023-11-01 03:28 UTC, merged