[WIP] ゲームシーンの追加
tricore-as14/TricoreTeamProject pull request #2
Opened 2023-10-19 03:07 UTC by tricore-as13

以下の作業を行いました。
・CSV読み込みによるステージ生成処理追加
・入力を受け取り具材生成
・初期化イベント、入力受け取り時のイベント追加

2023-10-19 04:20 UTC, tricore-as03 requested changes

2023-10-19 04:20 UTC, tricore-as03 commented on Assets/MyGameAssets/Script/Stage/CSVReader.cs
> +public class CSVReader : MonoBehaviour
[MUST]
ファイルの読み込みしかしないのであれば、MonoBehaviorを継承する必要はないかと。
ReadCSVDataをstaticにして汎用的な関数にしてしまえば、呼び出し側でも、わざわざメンバ変数として宣言する必要はなくなるかと。

MonoBehaviorの継承はコストが高いので、継承すべきかどうかは考えるよう意識していいただけると。

2023-10-19 04:20 UTC, tricore-as03 commented on Assets/MyGameAssets/Script/Stage/CSVReader.cs
> +            Debug.Log("CSVデータが見つかりませんでした");
[MUST]
エラーであれば、Debug.LogErrorを使用してください。

2023-10-19 04:20 UTC, tricore-as03 commented on Assets/MyGameAssets/Script/Stage/CSVReader.cs
> +        StringReader reader = new StringReader(csvFile.text);         // TextAssetをStringReaderに変換
[MUST]
StringReaderは、読み込みが完了して不要になった時点でClose関数を呼んで、ファイルを閉じてください。
https://qiita.com/karakuri-t910/items/dcf4350f956d52648ad3#%E3%82%B5%E3%83%B3%E3%83%97%E3%83%AB%E3%83%97%E3%83%AD%E3%82%B0%E3%83%A9%E3%83%A0streamreaderreadtoend

2023-10-19 04:20 UTC, tricore-as03 commented on Assets/MyGameAssets/Script/Stage/EventController.cs
> +    }
[MUST]
不要な関数は消してください。

2023-10-19 04:20 UTC, tricore-as03 commented on Assets/MyGameAssets/Script/Stage/ObjectGenerator.cs
> +    GameObject readObjectDate(int dataNumber)
[MUST]
関数は先頭大文字（アッパーキャメルケース）で書くように。
https://github.com/tricore-t-yui/tricore-wiki/wiki/Unity%E3%82%92%E4%BD%BF%E7%94%A8%E3%81%97%E3%81%9F%E9%96%8B%E7%99%BA%E6%99%82%E3%81%AEC%23%E3%82%B3%E3%83%BC%E3%83%86%E3%82%A3%E3%83%B3%E3%82%B0%E3%83%AB%E3%83%BC%E3%83%AB#uppercamelcase%E3%81%AB%E8%A9%B2%E5%BD%93%E3%81%99%E3%82%8B%E3%82%82%E3%81%AE

2023-10-19 04:20 UTC, tricore-as03 commented on Assets/MyGameAssets/Script/Stage/ObjectGenerator.cs
> +                return UpperBuns;
[MUST]
値を直接書くのはよくないです。
このままだと値が何を意味しているのかが分からないので、enumや定数を使用し、値を名前を付けてください。

2023-10-19 08:24 UTC, tricore-as03 commented
[MUST]
全てのクラスとクラスコメントの間が一行空いてしまっているので修正お願いします。

2023-10-19 08:53 UTC, tricore-as13 commented on Assets/MyGameAssets/Script/Stage/CSVReader.cs
> +
空白削除含め修正いたしました

2023-10-19 08:54 UTC, tricore-as13 commented on Assets/MyGameAssets/Script/Stage/ObjectGenerator.cs
> +                                cheesePrefab, puttyPrefab, UpperBuns;
修正いたしました。

2023-10-19 08:55 UTC, tricore-as13 commented on Assets/MyGameAssets/Script/Stage/ObjectGenerator.cs
> +        createObject.GetComponent<Rigidbody>().velocity = Vector3.zero;
コンポーネントを保持する変数をついかし、初めの入力時に、GetComponentで一度だけ保持するように修正しました。

2023-10-19 08:56 UTC, tricore-as13 commented on Assets/MyGameAssets/Script/Stage/CSVReader.cs
> +public class CSVReader : MonoBehaviour
継承をなしにし、静的メソッドに変更しました。

2023-10-19 08:56 UTC, tricore-as13 commented on Assets/MyGameAssets/Script/Stage/CSVReader.cs
> +            Debug.Log("CSVデータが見つかりませんでした");
修正いたしました。

2023-10-19 08:57 UTC, tricore-as13 commented on Assets/MyGameAssets/Script/Stage/EventController.cs
> +    }
修正いたしました。

2023-10-19 08:57 UTC, tricore-as13 commented on Assets/MyGameAssets/Script/Stage/ObjectGenerator.cs
> +    GameObject readObjectDate(int dataNumber)
修正いたしました。

2023-10-19 09:00 UTC, tricore-as13 commented on Assets/MyGameAssets/Script/Stage/ObjectGenerator.cs
> +                return UpperBuns;
enum型で値に名前付けし、キャストでintとしてcaseの比較として扱うように処理を変更しました。

2023-10-20 02:19 UTC, tricore-as03 approved these changes
LGTM

2023-10-20 02:27 UTC, merged