ゲームクリア時のエフェクト追加
tricore-as14/TricoreTeamProject pull request #7
Opened 2023-10-24 06:47 UTC by tricore-as13

・ゲームクリア、オーバー時のイベント呼び出しが複数回呼び出される不備を修正
・クリアエフェクトの追加
・エフェクトの生成と再生までの処理実装
・上記の処理をクリアイベントに追加

2023-10-24 08:02 UTC, tricore-as03 requested changes

2023-10-24 08:02 UTC, tricore-as03 commented on Assets/MyGameAssets/Script/Stage/ClearEffectController.cs
> +        particle.Play();
[Q]
再生終了後も生成したオブジェクトは残ったままになりそうですが問題ないでしょうか？

2023-10-24 08:06 UTC, tricore-as13 commented on Assets/MyGameAssets/Script/Stage/StageManager.cs
> +    bool callGameEndEventFlg = false;
確かにこれから増える可能性も考えるとenumに置き換えるのが最善だと思いました。
変更します。

2023-10-24 08:07 UTC, tricore-as13 commented on Assets/MyGameAssets/Script/Stage/ClearEffectController.cs
> +        particle.Play();
このパーティクルはクリア後に一度しか生成されなくすぐシーン読み込みが入るのでこのままでよいかと思い削除処理を入れていません。

2023-10-24 08:17 UTC, tricore-as13 commented on Assets/MyGameAssets/Script/Stage/StageManager.cs
> +    bool callGameEndEventFlg = false;
callCountDownEventFlgが必要処理のなかで必要がなくなったため削除しました。

2023-10-24 08:25 UTC, tricore-as13 commented on Assets/MyGameAssets/Script/Stage/EventController.cs
> +        gameOverEvent += RemoveAllEvent;                          // すべてのイベントの解放
修正いたしました。

2023-10-24 09:07 UTC, tricore-as03 commented on Assets/MyGameAssets/Script/Stage/ClearEffectController.cs
> +        particle.Play();
了解です。であれば問題ないかと。

2023-10-25 01:53 UTC, tricore-as13 commented on Assets/MyGameAssets/Script/Stage/StageManager.cs
> +    bool callGameEndEventFlg = false;
ゲームクリア、オーバーの管理をenumでの管理に変更しました。

2023-10-25 02:02 UTC, tricore-as03 requested changes

2023-10-25 02:02 UTC, tricore-as03 commented on Assets/MyGameAssets/Script/Stage/ClearEffectController.cs
> +public class ClearEffectController : MonoBehaviour
[MUST]
後だしで申し訳ないですが、クラス名の意味が広すぎるのでもう少し具体的な名前を付けてくれると。
「Controller」だと何を処理しているのか分かりにくいです。
今回でいえば、エフェクトの再生しかしていないので「ClearEffectPlayer」とかでいいと思います。

2023-10-25 02:07 UTC, tricore-as13 commented on Assets/MyGameAssets/Script/Stage/ClearEffectController.cs
> +public class ClearEffectController : MonoBehaviour
[ClearEffectPlayer]へ変更いたしました。

2023-10-25 02:12 UTC, tricore-as03 requested changes

2023-10-25 02:12 UTC, tricore-as03 commented on Assets/MyGameAssets/Script/Stage/EventController.cs
> +    [SerializeField] ClearEffectPlayer clearEffectController;
[MUST]
クラス名修正したら変数名の修正もお願いします。
また、SerializeFieldの変数名を変えると、インスペクタ側のアタッチが外れてしまうので気を付けていただけると。

2023-10-25 02:19 UTC, tricore-as13 commented on Assets/MyGameAssets/Script/Stage/EventController.cs
> +    [SerializeField] ClearEffectPlayer clearEffectController;
変数名、アッタッチしてるオブジェクト名の変更、再アタッチいたしました。

2023-10-25 02:22 UTC, tricore-as03 approved these changes
LGTM

2023-10-25 02:23 UTC, merged